### ISSUE TITLE
Website not getting redirect?

### ISSUE THREAD

**Issue by developermoz** [trekhleb/homemade-machine-learning#22]
Hello How are you?

Its my eager request to you that mine website http://www.windowsmoviemaker.xyz/ is not getting redirect to SSl https://www.windowsmoviemaker.xyz/ ? I have installed Really simple SSl but not able to get the issue solved till now?
This is my website : [Windows Movie maker](https://www.windowsmoviemaker.xyz/)

**Comment by ashudva** [comment]
I don't think your issue is relevant to this repository.
