### ISSUE TITLE
Predictions

### ISSUE THREAD

**Issue by logan-lieou** [trekhleb/homemade-machine-learning#29]
Is there no module such that you could make predictions on new data for K-Means?

**Comment by Anikatkumar** [comment]
what do you exactly mean?

**Comment by AliHaider20** [comment]
> Is there no module such that you could make predictions on new data for K-Means?

Can you elaborate it more.

**Comment by logan-lieou** [comment]
To be honest that was a long time ago I have no idea what I was thinking about 2 years ago.
