### ISSUE TITLE
An error in "Math | Logistic Regression"

### ISSUE THREAD

**Issue by ghosthamlet** [trekhleb/homemade-machine-learning#3]
In the [section:] Hypothesis (the Model) (https://github.com/trekhleb/homemade-machine-learning/tree/master/homemade/logistic_regression#hypothesis-the-model), 
Under this line "Now we my write down the hypothesis as follows:"
**Predict y = 0 ... < 0.5 ... >= 0, Predict y = 1 ... > 0.5 ... < 0**,
may should be  **... < 0.5 ... < 0,  ... >= 0.5 ... >= 0**

**Comment by trekhleb** [comment]
@ghosthamlet , thanks for noticing that! It is fixed now.
